### ISSUE TITLE
could not be installed

### ISSUE THREAD

**Issue by iso-lib** [gemini86/node-red-contrib-chart-image#27]
OS:alpine 3.18 
Node-Red:~# npm -v
9.6.6
Node-Red:~# node -v
v20.8.1
Node-Red:~# 

2024-02-08T08:26:59.488Z 安装 : node-red-contrib-chart-image 1.2.0

2024-02-08T08:26:59.537Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production --engine-strict node-red-contrib-chart-image@1.2.0
2024-02-08T08:27:00.439Z [err] npm
2024-02-08T08:27:00.440Z [err]  WARN config production Use `--omit=dev` instead.
2024-02-08T08:27:10.337Z [err] npm
2024-02-08T08:27:10.337Z [err]  ERR! code 1
2024-02-08T08:27:10.337Z [err] npm ERR! path /root/.node-red/node_modules/canvas
2024-02-08T08:27:10.341Z [err] npm ERR! command failed
2024-02-08T08:27:10.341Z [err] npm ERR! command sh -c node-pre-gyp install --fallback-to-build --update-binary
2024-02-08T08:27:10.341Z [err] npm ERR!
2024-02-08T08:27:10.342Z [err]  Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --update-binary --module=/root/.node-red/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/root/.node-red/node_modules/canvas/build/Release --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v115 --python=/usr/bin/python3' (1)
2024-02-08T08:27:10.342Z [err] npm ERR! node-pre-gyp info it worked if it ends with ok
2024-02-08T08:27:10.342Z [err] npm ERR! node-pre-gyp info using node-pre-gyp@1.0.11
2024-02-08T08:27:10.342Z [err] npm
2024-02-08T08:27:10.342Z [err]  ERR! node-pre-gyp info using node@20.8.1 | linux | x64
2024-02-08T08:27:10.342Z [err] npm ERR!
2024-02-08T08:27:10.343Z [err]  node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v115-linux-musl-x64.tar.gz
2024-02-08T08:27:10.343Z [err] npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v115-linux-musl-x64.tar.gz 
2024-02-08T08:27:10.343Z [err] npm ERR! node-pre-gyp WARN Pre-built binaries not installable for canvas@2.11.2 and node@20.8.1 (node-v115 ABI, musl) (falling back to source compile with node-gyp) 
2024-02-08T08:27:10.343Z [err] npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v115-linux-musl-x64.tar.gz 
2024-02-08T08:27:10.343Z [err] npm ERR!
2024-02-08T08:27:10.343Z [err]  gyp info it worked if it ends with ok
2024-02-08T08:27:10.343Z [err] npm ERR! gyp info using node-gyp@9.3.1
2024-02-08T08:27:10.343Z [err] npm ERR! gyp info using node@20.8.1 | linux | x64
2024-02-08T08:27:10.343Z [err] npm
2024-02-08T08:27:10.343Z [err]  ERR! gyp info ok 
2024-02-08T08:27:10.343Z [err] npm ERR! gyp info it worked if it ends with ok
2024-02-08T08:27:10.343Z [err] npm 
2024-02-08T08:27:10.343Z [err] ERR! gyp info using node-gyp@9.3.1
2024-02-08T08:27:10.343Z [err] npm ERR! gyp info using node@20.8.1 | linux | x64
2024-02-08T08:27:10.343Z [err] npm 
2024-02-08T08:27:10.343Z [err] ERR! gyp ERR! find Python 
2024-02-08T08:27:10.343Z [err] npm ERR! gyp ERR! find Python checking Python explicitly set from command line or npm configuration
2024-02-08T08:27:10.343Z [err] npm 
2024-02-08T08:27:10.344Z [err] ERR! gyp ERR! find Python - "--python=" or "npm config get python" is "/usr/bin/python3"
2024-02-08T08:27:10.344Z [err] npm ERR! gyp ERR! find Python - "/usr/bin/python3" is not in PATH or produced an error
2024-02-08T08:27:10.344Z [err] npm ERR! gyp ERR! find Python Python is not set from environment variable PYTHON
2024-02-08T08:27:10.344Z [err] npm ERR! gyp ERR! find Python checking if "python3" can be used
2024-02-08T08:27:10.344Z [err] npm ERR!
2024-02-08T08:27:10.344Z [err]  gyp ERR! find Python - "python3" is not in PATH or produced an error
2024-02-08T08:27:10.344Z [err] npm ERR! gyp ERR! find Python checking if "python" can be used
2024-02-08T08:27:10.344Z [err] npm ERR! gyp ERR! find Python - "python" is not in PATH or produced an error
2024-02-08T08:27:10.344Z [err] npm ERR! gyp ERR! find Python 
2024-02-08T08:27:10.344Z [err] npm ERR!
2024-02-08T08:27:10.344Z [err]  gyp ERR! find Python **********************************************************
2024-02-08T08:27:10.344Z [err] npm ERR! gyp ERR! find Python You need to install the latest version of Python.
2024-02-08T08:27:10.344Z [err] npm ERR!
2024-02-08T08:27:10.344Z [err]  gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
2024-02-08T08:27:10.344Z [err] npm ERR! gyp ERR! find Python you can try one of the following options:
2024-02-08T08:27:10.344Z [err] npm ERR!
2024-02-08T08:27:10.345Z [err]  gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
2024-02-08T08:27:10.345Z [err] npm ERR! gyp ERR! find Python   (accepted by both node-gyp and npm)
2024-02-08T08:27:10.345Z [err] npm ERR!
2024-02-08T08:27:10.345Z [err]  gyp ERR! find Python - Set the environment variable PYTHON
2024-02-08T08:27:10.345Z [err] npm ERR! gyp ERR! find Python - Set the npm configuration variable python:
2024-02-08T08:27:10.345Z [err] npm ERR!
2024-02-08T08:27:10.345Z [err]  gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
2024-02-08T08:27:10.345Z [err] npm ERR! gyp ERR! find Python For more information consult the documentation at:
2024-02-08T08:27:10.345Z [err] npm ERR!
2024-02-08T08:27:10.345Z [err]  gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
2024-02-08T08:27:10.345Z [err] npm ERR! gyp ERR! find Python **********************************************************
2024-02-08T08:27:10.345Z [err] npm ERR!
2024-02-08T08:27:10.345Z [err]  gyp ERR! find Python 
2024-02-08T08:27:10.345Z [err] npm ERR! gyp ERR! configure error 
2024-02-08T08:27:10.345Z [err] npm ERR!
2024-02-08T08:27:10.345Z [err]  gyp ERR! stack Error: Could not find any Python installation to use
2024-02-08T08:27:10.345Z [err] npm ERR! gyp ERR! stack     at PythonFinder.fail (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:330:47)
2024-02-08T08:27:10.345Z [err] npm ERR!
2024-02-08T08:27:10.346Z [err]  gyp ERR! stack     at PythonFinder.runChecks (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:159:21)
2024-02-08T08:27:10.346Z [err] npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:202:16)
2024-02-08T08:27:10.346Z [err] npm 
2024-02-08T08:27:10.346Z [err] ERR! gyp ERR! stack     at PythonFinder.execFileCallback (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:294:16)
2024-02-08T08:27:10.346Z [err] npm ERR! gyp ERR! stack     at exithandler (node:child_process:430:5)
2024-02-08T08:27:10.346Z [err] npm 
2024-02-08T08:27:10.346Z [err] ERR! gyp ERR! stack     at ChildProcess.errorhandler (node:child_process:442:5)
2024-02-08T08:27:10.346Z [err] npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:514:28)
2024-02-08T08:27:10.346Z [err] npm 
2024-02-08T08:27:10.346Z [err] ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:292:12)
2024-02-08T08:27:10.346Z [err] npm ERR! gyp ERR! stack     at onErrorNT (node:internal/child_process:484:16)
2024-02-08T08:27:10.346Z [err] npm 
2024-02-08T08:27:10.346Z [err] ERR! gyp ERR! stack     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
2024-02-08T08:27:10.346Z [err] npm ERR! gyp ERR! System Linux 5.19.17-pve
2024-02-08T08:27:10.346Z [err] npm ERR!
2024-02-08T08:27:10.346Z [err]  gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--update-binary" "--module=/root/.node-red/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/root/.node-red/node_modules/canvas/build/Release" "--napi_version=9" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v115" "--python=/usr/bin/python3"
2024-02-08T08:27:10.346Z [err] npm ERR! gyp ERR! cwd /root/.node-red/node_modules/canvas
2024-02-08T08:27:10.346Z [err] npm ERR!
2024-02-08T08:27:10.346Z [err]  gyp ERR! node -v v20.8.1
2024-02-08T08:27:10.346Z [err] npm ERR! gyp ERR! node-gyp -v v9.3.1
2024-02-08T08:27:10.346Z [err] npm 
2024-02-08T08:27:10.347Z [err] ERR! gyp ERR! not ok 
2024-02-08T08:27:10.347Z [err] npm ERR! node-pre-gyp ERR! build error 
2024-02-08T08:27:10.347Z [err] npm 
2024-02-08T08:27:10.347Z [err] ERR! node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --update-binary --module=/root/.node-red/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/root/.node-red/node_modules/canvas/build/Release --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v115 --python=/usr/bin/python3' (1)
2024-02-08T08:27:10.347Z [err] npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/root/.node-red/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
2024-02-08T08:27:10.347Z [err] npm 
2024-02-08T08:27:10.347Z [err] ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:514:28)
2024-02-08T08:27:10.347Z [err] npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1105:16)
2024-02-08T08:27:10.347Z [err] npm 
2024-02-08T08:27:10.347Z [err] ERR! node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:305:5)
2024-02-08T08:27:10.347Z [err] npm ERR! node-pre-gyp ERR! System Linux 5.19.17-pve
2024-02-08T08:27:10.347Z [err] npm 
2024-02-08T08:27:10.347Z [err] ERR! node-pre-gyp ERR! command "/usr/bin/node" "/root/.node-red/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--update-binary"
2024-02-08T08:27:10.347Z [err] npm ERR! node-pre-gyp ERR! cwd /root/.node-red/node_modules/canvas
2024-02-08T08:27:10.347Z [err] npm
2024-02-08T08:27:10.347Z [err]  ERR! node-pre-gyp ERR! node -v v20.8.1
2024-02-08T08:27:10.347Z [err] npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.11
2024-02-08T08:27:10.347Z [err] npm
2024-02-08T08:27:10.348Z [err]  ERR! node-pre-gyp ERR! not ok
2024-02-08T08:27:10.353Z [err] 
2024-02-08T08:27:10.354Z [err] npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2024-02-08T08_27_00_342Z-debug-0.log
2024-02-08T08:27:10.371Z rc=1

**Comment by dmachadol** [comment]
ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v115-linux-musl-x64.tar.gz 

Github link broken image not exists. there are new images. perhaps 
canvas-v2.11.2-node-v115-win32-unknown-x64.tar.gz  are valid?
